import pyvisa

def list_devices()->list:
    # randomly return one of 4 autogenerated lists for testing purposes
    # this is a placeholder for the actual implementation that lists devices
    # connected to the system using PyVISA
    # This function returns a list of dictionaries with device address and description
    return [{'address': 'USB0::0x1234::0x5678::INSTR', 'description': 'Device 1'},
            {'address': 'GPIB::0x1234::0x5678::INSTR', 'description': 'Device 2'},
            {'address': 'SERIAL::0x1234::0x5678::INSTR', 'description': 'Device 3'},]
    # Initialize the resource manager and list all resources    
    
    
    rm = pyvisa.ResourceManager()
    devices = rm.list_resources()
    device_list = []
    for device in devices:
        if not device.startswith('GPIB'):
            try:
                resource = rm.open_resource(device)
                device_info = {
                    'address': device,
                    'description': resource.query('*IDN?')
                }
                device_list.append(device_info)
            except Exception as e:
                print(f"Error accessing {device}: {e}")
    return device_list